### ISSUE TITLE
test with more ontologies

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/simplifyEnrichment#11]
tested:

- [x] GO BP
- [x] DO
- [x] KEGG
- [x] Reactome

More to test

- [x] MsigDB
- [x] mixed from multiple ontologies

**Comment by selcant** [comment]
Hi! Can we use KEGG/Reactome ontologies with the development version?

**Comment by jokergoo** [comment]
You can use other ontology databases, but they do not work as well as GO. See results at https://simplifyenrichment.github.io/examples/

The main problems are:

1. In the simplifyEnrichment paper, it shows the semantic similarity works very well, which is only workable for GO terms, but not for KEGG/Reactome terms. For KEGG/Reactome terms, you can only calculate similarities purely by gene overlap, which normally do not have such "diagonal block" patterns which are used to cluster terms.
2. for KEGG pathways, I think it not necessary to cluster them. Normally you will not have too many enriched pathways, say, around 20 or 40, which you can already read them one by one. And terms less than 50 are not suggested to cluster.

**Comment by selcant** [comment]
Thank you! I think I figured it out. Unfortunately I do end up with many KEGG/Reactome terms (>100) in some cases and need to simplify. From what I can see KEGG clustering worked very well, clear diagonal. Trying to get the reactome clustering to work, running into some errors at the moment. Will open a separate issue if I can't make it work. Thanks again for the reply.
