### ISSUE TITLE
New feature request for simplifyGOFromMultipleLists

### ISSUE THREAD

**Issue by frylhc** [jokergoo/simplifyEnrichment#110]
Hi jokergoo,

Thank you for developing such a great tool for tidying GO enrichment results — it has been incredibly helpful for my work! When using simplifyGOFromMultipleLists, I noticed that the left heatmap displays the adjusted p-values for each GO term across groups. However, in some cases, it might be more insightful to use NES values instead of p-values, as this would provide clearer information on the direction of gene expression changes. I was wondering if incorporating this feature might be considered in a future update of the package.

Thanks again for your amazing tool!

**Comment by jokergoo** [comment]
I think it is possible. `simplifyGOFromMultipleLists()` is a wrapper on `simplifyGO()` which actually allows to add more self-defined heatmaps. 

It will be supported in the future. Thanks!
