### ISSUE TITLE
Custom color ramp for simplifyGO() ?

### ISSUE THREAD

**Issue by dpleone** [jokergoo/simplifyEnrichment#35]
Hi there,
Fantastic work with the package! Is there a way to easily pass a custom color ramp to the simplifyGO() function? E.g. change the heatmap from shades of red to blue.
Best

**Comment by jokergoo** [comment]
Yes, just supported.

You can set `col` argument with a vector of colors. The colors interpolate from 0 to the 95th percentile of the similarity matrix.
