### ISSUE TITLE
Can this package be applied to scRNA-seq or scATAC-seq?

### ISSUE THREAD

**Issue by eleozzr** [jokergoo/simplifyEnrichment#36]
This is an awesome package!!! Based on your example, you give a similarity matrix among different GO terms.  But I am considering that can this package be applied to scRNA-seq data.  For example, If I want to plot a figure that the left panel shows a similarity matrix between cells and the right panel shows some corresponding  GO terms or word could of GO terms? 

![image](https://user-images.githubusercontent.com/33725620/96564526-d4b74480-12f5-11eb-99a2-8365acfe9e08.png)

**Comment by jokergoo** [comment]
Sorry I didn't see your question! This is a new project and the new issues are easily be ignored by the massive issues from my other projects.

Yes, this is a good suggestion! In this case, we don't need to cluster the GO terms, but direclty use the GO list for each cell cluster, which is basically a use of GO word cloud annotation. 

I will think about it. Thank you!

**Comment by jokergoo** [comment]
Now I have updated the package and added a new vignette of how to add a general word cloud annotation to heatmaps: https://jokergoo.github.io/simplifyEnrichment/articles/word_cloud_anno.html
