### ISSUE TITLE
Custom font and background color for word cloud

### ISSUE THREAD

**Issue by chiayic** [jokergoo/simplifyEnrichment#37]
Hello,
Really great and useful tool. Thanks a lot!
I was trying to change the font color in the word cloud using **word_cloud_grob_param**
```
simplifyGO(mat,draw_word_cloud=T,
           word_cloud_grob_param=(col = 1))
```
Somehow it didn't work and still return the default random color without warning nor error message. I couldn't see which part went wrong. Your insight would be much appreciated.

Also, is it possible to change the background of the word cloud from the default grey scheme?

Thank you again,
Chia-Yi

**Comment by jokergoo** [comment]
Sorry I didn't see your question! This is a new project and the new issues are easily be ignored by the massive issues from my other projects.

Currently, the support for the word cloud is limited in the `simplifyGO()` function, but I will support them in the future.

**Comment by jokergoo** [comment]
1. the value for `word_cloud_grob_param` should be a list:

```r
simplifyGO(mat,draw_word_cloud=T,
           word_cloud_grob_param=list(col = 1))  # add `list` here
```

2. Now I have added `bg_gp` argument in the function so you can control the background colors as well as the border colors.

```r
simplifyGO(mat, word_cloud_grob_param=list(col = "white"), bg_gp = gpar(fill = "orange", col = "blue", lty = 2))
```

![image](https://user-images.githubusercontent.com/449218/103273746-54c9ec80-49c0-11eb-8c5a-f0fac1269bba.png)
