### ISSUE TITLE
Make the default colors colour-blind tolerable

### ISSUE THREAD

**Issue by krassowski** [jokergoo/simplifyEnrichment#54]
The default random colors are difficult to read with the default background. It's great that those are all customizable, but just in case if someone is going to leave it as is, and for the ease of exploratory analysis I would love to be able to read the text clearly.

In the following example:

![image](https://user-images.githubusercontent.com/5832902/120822900-c3523e00-c54e-11eb-9a17-3dd78a123047.png)

I am unable to read the words:
- between "economy" and "indonesia" in (g)
- first, seventh, and eight word in (e)
- a word in (c) between "crude" and "canada"

https://github.com/jokergoo/simplifyEnrichment/blob/3dbbaf52e68ba6e81bb3c2126dd15770f8d718d8/R/word_count.R#L156-L159

**Comment by jokergoo** [comment]
This is mainly because all colors are random. I think it can be solved by changing the colors if they are too light.

**Comment by jokergoo** [comment]
Now I check whether the random colors are bright or yellow. If they are, new random colors will be regenerated.
