### ISSUE TITLE
Colour the same words with the same colour

### ISSUE THREAD

**Issue by krassowski** [jokergoo/simplifyEnrichment#55]
This is just a suggestion, but I think that having the same words have the same colour would be a nice addition. Currently they are completely random (which is different to what I expected):

![image](https://user-images.githubusercontent.com/5832902/120823628-85094e80-c54f-11eb-8be0-7547fcdd42eb.png)

**Comment by jokergoo** [comment]
This is done!

![image](https://user-images.githubusercontent.com/449218/129721144-bf379bab-36a2-4f24-a7b4-97b023429d00.png)
