### ISSUE TITLE
Expand GO_similarity to work also with GO terms

### ISSUE THREAD

**Issue by christianholland** [jokergoo/simplifyEnrichment#7]
Hi,

very nice package, congrats!

I wonder whether it would be possible that the function `GO_similarity` accepts beside GO **IDs** also GO **terms**?

E.g. `GO_POSITIVE_REGULATION_OF_VIRAL_TRANSCRIPTION` instead of  `GO:0050434`.

I think this feature would brighten the scope of the package a lot as for instance msigdb provides in the download section only the terms and not the IDs.

Thanks,
Christian

**Comment by jokergoo** [comment]
Sorry I didn't see your comment!

This package is in the early development stage. Currently the similarity matrix is calculated by GOSemSim package which only allows the GO IDs. But yes, in the future more general ontologies will be supported.
