### ISSUE TITLE
Add bar plot to simplifyGOFromMultipleLists

### ISSUE THREAD

**Issue by jelman** [jokergoo/simplifyEnrichment#88]
Hello,

In the example output in this [vignette ](https://jokergoo.github.io/simplifyEnrichment/articles/simplifyEnrichment.html#apply-to-multiple-lists-of-go-ids) there are bar plots to the left showing how many significant GO terms are in each cluster per list. I don't see an option to include this in the simplifyGOFromMultipleLists function though. Is there a way to do this?

Thanks!
Jeremy

**Comment by jwlsyxff** [comment]
I encountered the same question as yours at first as the heatmap didn't include the bat plots at left, and then I figured out that we needed to download the lastest version directly from GitHub as 
library(devtools)
install_github("jokergoo/simplifyEnrichment")
then the heatmap will contain bar plots
